"use strict";
exports.__esModule = true;
require("reflect-metadata");
var inversify_1 = require("inversify");
var MongoDataRepository_1 = require("./src/repository/implementation/MongoDataRepository");
var SqlDataRepository_1 = require("./src/repository/implementation/SqlDataRepository");
var container = new inversify_1.Container({ defaultScope: "Singleton" });
container.bind("dataRepository").to(MongoDataRepository_1["default"]).inSingletonScope();
container.bind("dataRepository").to(SqlDataRepository_1["default"]).inSingletonScope();
exports["default"] = container;
